version: '3'
services:
  web:
    container_name: Flask
    volumes:
      - ./:/project
    build:
      context:
        .
      dockerfile:
        Web.Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - mysql
      - redis
      - celery
    depends_on:
      - mysql
      - redis
      - celery
  redis:
    container_name: Redis
    image: redis:latest
    ports:
     - 6379:6379
    expose:
      - 6379
  mysql:
    container_name: MySQL
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=oruri448
      - MYSQL_DATABASE=realty
  celery:
    container_name: Celery
    volumes:
      - ./:/project
    build:
      context:
        .
      dockerfile:
        Celery.Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
      - CELERY_APP=tasks
    command: celery -A tasks worker -l info