version: '3'
services:

  web:
    container_name: Flask
    volumes:
      - ./:/project
    build:
      context:
        .
      dockerfile:
        Web.Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - mysql
      - redis
      - celery
      - selenium-hub
    depends_on:
      - mysql
      - redis
      - celery
      - selenium-hub
    command: python -u /project/main.py


  redis:
    container_name: Redis
    image: redis:latest
    ports:
     - 6379:6379
    expose:
      - 6379


  mysql:
    container_name: MySQL
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=oruri448
      - MYSQL_DATABASE=realty


  celery:
    container_name: Celery
    volumes:
      - ./:/project
    build:
      context:
        .
      dockerfile:
        Celery.Dockerfile
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - CELERY_TASK_SERIALIZER=json
      - CELERY_RESULT_SERIALIZER=json
      - CELERY_APP=tasks
    links:
      - mysql
      - selenium-hub
    depends_on:
      - mysql
      - selenium-hub
    command: celery -A tasks worker -l info


  selenium-hub:
    container_name: selenium-hub
    image: selenium/hub
    ports:
      - 4444:4444
    expose:
      - 4444


  chrome-node:
    container_name: chrome-node
    image: selenium/node-chrome
    environment:
      - HUB_PORT_4444_TCP_ADDR=selenium-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - REGISTER=TRUE
    links:
      - selenium-hub:hub
    expose:
      - 5555
    volumes:
    - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
