version: '3'
services:
  web:
    volumes:
      - ./:/code
    build:
      .
    expose:
      - 5000
    ports:
      - 5000:5000
    links:
      - mysql
      - redis
  redis:
    image: "redis:latest"
    ports:
     - 6379:6379
    expose:
      - 6379
  mysql:
    image: "mysql:latest"
    ports:
      - 3306:3306
    expose:
      - 3306
    environment:
      - MYSQL_ROOT_PASSWORD=oruri448
      - MYSQL_DATABASE=realty
